import uid from 'utils/lib/uid';
import ktv from 'utils/lib/ktv';

const ACTIONS = [
  'SHOW_NOTEBOOK_EDITOR',
  'HIDE_NOTEBOOK_EDITOR',

  'CREATE_NOTEBOOK',
  'CREATE_NOTEBOOK_OK',
  'CREATE_NOTEBOOK_FAILED',

  'UPDATE_NOTEBOOK',
  'UPDATE_NOTEBOOK_OK',
  'UPDATE_NOTEBOOK_FAILED',

  'FETCH_NOTEBOOKS',
  'FETCH_NOTEBOOKS_OK',
  'FETCH_NOTEBOOKS_FAILED'
];

export default ktv(ACTIONS, uid);
